<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Process\Exceptions\ProcessTimedOutException;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Str;

class MakeCatalogSubmodule extends Command
{
    protected $signature = 'module:make-submodule
        {module : Top-level module name, e.g. General}
        {submodule : Submodule name from the catalog, e.g. Pegawai}
        {--as= : English name for the generated module/class (e.g. Employee). Required the first time a submodule is scaffolded; reused automatically afterwards}';

    protected $description = 'Scaffold a Laravel module for one catalog submodule (config/module-catalog.php is the source of truth for validity, config/module-name-translations.php for the English name)';

    private function translationsPath(): string
    {
        return config_path('module-name-translations.php');
    }

    private function loadTranslations(): array
    {
        $path = $this->translationsPath();

        return is_file($path) ? require $path : [];
    }

    private function saveTranslation(string $module, string $submodule, string $englishName): void
    {
        $translations = $this->loadTranslations();
        $translations[$module][$submodule] = $englishName;

        ksort($translations);
        foreach ($translations as &$subs) {
            ksort($subs);
        }

        $export = var_export($translations, true);
        File::put($this->translationsPath(), "<?php\n\nreturn {$export};\n");
    }

    public function handle(): int
    {
        $module = $this->argument('module');
        $submodule = $this->argument('submodule');

        $catalog = config('module-catalog');
        $known = collect($catalog[$module] ?? []);

        if (! $known->contains($submodule)) {
            $this->error("'{$module}/{$submodule}' bukan pasangan module/submodule yang valid di katalog.");

            if (! $known->isEmpty()) {
                $suggestions = $known->filter(fn ($s) => Str::contains(Str::lower($s), Str::lower(substr($submodule, 0, 3))))->take(5);
                if ($suggestions->isNotEmpty()) {
                    $this->line('Mirip: '.$suggestions->implode(', '));
                }
            } elseif (! array_key_exists($module, $catalog)) {
                $this->line('Modul tidak dikenal: '.$module.'. Modul valid: '.implode(', ', array_keys($catalog)));
            }

            return self::FAILURE;
        }

        $translations = $this->loadTranslations();
        $englishName = $this->option('as') ?: ($translations[$module][$submodule] ?? null);

        if (! $englishName) {
            $this->error("Belum ada nama Inggris buat '{$module}/{$submodule}'. Kasih pakai --as=NamaInggris (contoh: --as=Employee).");

            return self::FAILURE;
        }

        $englishName = Str::studly($englishName);

        if (isset($translations[$module][$submodule]) && $translations[$module][$submodule] !== $englishName) {
            $this->warn("Sebelumnya '{$module}/{$submodule}' pernah diterjemahkan jadi '{$translations[$module][$submodule]}', sekarang di-override jadi '{$englishName}'.");
        }

        // nwidart normalizes the module directory name to StudlyCase internally regardless
        // of separators in the given name, and does so inconsistently between path creation
        // and module lookup when given a hyphenated name (crashes with "fireEvent() on null")
        // — so we pre-compute the final studly form ourselves and pass that directly, keeping
        // directory/namespace/module.json name/modules_statuses.json key all identical.
        $name = Str::studly($module).$englishName;

        try {
            // CachedFileRepository serves the module list from bootstrap/cache/module-manifest.php,
            // so a stale manifest would keep module:make's sub-generators from seeing the brand-new
            // module folder (they re-resolve it via findOrFail right after scaffolding it). Drop the
            // cached manifest + in-memory memo first so the repository falls back to scanning disk,
            // then module:manifest-cache at the end re-warms it.
            $this->call('module:manifest-cache', ['--clear' => true]);
            app('modules')->resetModules();

            $this->call('module:make', [
                'name' => [$name],
                '--api' => true,
            ]);
        } catch (\Exception $e) {
            $this->warn('module:make threw an exception: ' . $e->getMessage());
            $this->warn('Continuing scaffold anyway...');
            // module:make's own internal `composer dump-autoload` call hits the Symfony
            // Process default 60s timeout once there are dozens of module composer.json
            // files for the merge-plugin to scan. The module itself is already fully
            // generated by this point — just re-run autoload dump with headroom.
            $this->warn('composer dump-autoload internal ke module:make timeout, ngulang manual dengan timeout lebih panjang...');
            Process::path(base_path())->timeout(300)->run('composer dump-autoload');
        }

        $this->stripUnusedScaffold($name);
        $this->saveTranslation($module, $submodule, $englishName);

        // module:make never touches composer's autoload map (no Modules\ PSR-4 in the root
        // composer.json), so without this the fresh module's namespaces aren't loadable and
        // module-provider compilation dies with "Class ...ServiceProvider not found". Dump here,
        // after the scaffolds, so scan picks up the new module folder.
        $dump = Process::path(base_path())->timeout(300)->run('composer dump-autoload --no-interaction');

        if (! $dump->successful()) {
            $this->error('composer dump-autoload gagal setelah scaffold: '.$dump->errorOutput());

            return self::FAILURE;
        }

        $this->call('module:manifest-cache');

        $this->info("Modul {$name} siap (sumber katalog: {$module}/{$submodule}). Namespace: Modules\\{$name}");

        return self::SUCCESS;
    }

    /**
     * `module:make --api` still generates resources/views, resources/assets, vite.config.js,
     * package.json, routes/web.php and config/config.php regardless of config/modules.php's
     * generator.*.generate=false toggles (that config only governs individual `module:make-*`
     * sub-generators, not this one). This app is API-only with no per-module custom config, so
     * drop the dead weight immediately - an empty config/config.php in particular is a real,
     * multiplying-with-module-count cost: ModuleServiceProvider::registerConfig() walks it with
     * a RecursiveDirectoryIterator and merges it into config() on every single boot.
     */
    private function stripUnusedScaffold(string $name): void
    {
        $path = base_path("Modules/{$name}");

        foreach (['resources', 'vite.config.js', 'package.json', 'config', 'routes/web.php'] as $item) {
            $target = "{$path}/{$item}";
            is_dir($target) ? File::deleteDirectory($target) : @unlink($target);
        }
    }
}
