<?php

// Source of truth: scanned from the legacy SIMGOS codebase (35 modules, 675 submodules).
// Manual additions: General.Agama, General.JenisKelamin, General.Profesi, General.Pendidikan,
// General.Pekerjaan, General.StatusPerkawinan, General.Suku, General.Bahasa, General.Kelas,
// General.Smf, General.JenisTindakan, General.JenisRuangan
// — these don't exist as standalone REST submodules in the source (SIMGOS stores them as
// JENIS-coded rows in one generic General/Referensi table instead, or - for Smf/JenisTindakan/
// JenisRuangan - only as a referenced-but-never-defined foreign key: DokterSMF/SMFRuangan/
// Pegawai.smf_id, General/Tindakan.type_id, General/Ruangan.type_id), added here so they can be
// scaffolded as proper normalized tables via module:make-submodule like everything else.
//
// Intentional exclusions — do NOT scaffold these, they were deliberately removed (2026-08-24)
// per project rule "1 referensi = 1 modul":
//   General.Referensi     — one generic table holding many JENIS-coded datasets (EAV-style);
//                           rejected. Its datasets live as their own modules instead (Agama,
//                           JenisKelamin, Profesi, ..., see manual additions above).
//   General.JenisReferensi— merely lists the JENIS codes of that generic table.
//   General.Map           — empty stub upstream (entity without properties, all writes → 405).
return [
    'Aplikasi' => ['AllowIP', 'Authentication', 'GroupPenggunaAksesModule', 'Images', 'InfoTeks', 'Instansi', 'Modules', 'Objek', 'PemeriksaanSaluranCernahAtas', 'Pengguna', 'PenggunaAkses', 'PenggunaAksesLog', 'PenggunaAksesRuangan', 'PenggunaLog', 'PenggunaRequestLog', 'Petunjuk', 'PropertiConfig', 'Sinkronisasi', 'Teams', 'Tentang'],
    'Application' => ['Controller'],
    'BPJS' => ['ICare/Validate', 'SmartClaim/Klaim'],
    'BPJService' => ['Aplicares', 'Kunjungan', 'LPK', 'Monitoring', 'PRB', 'Peserta', 'Referensi', 'RencanaKontrol', 'Rujukan', 'VClaim/v_1_0/Service', 'VClaim/v_1_1/Service', 'VClaim/v_2_0/LPKService', 'VClaim/v_2_0/MonitoringService', 'VClaim/v_2_0/PRBService', 'VClaim/v_2_0/PesertaService', 'VClaim/v_2_0/ReferensiService', 'VClaim/v_2_0/RencanaKontrolService', 'VClaim/v_2_0/RujukanService', 'VClaim/v_2_0/SEPService', 'VClaim/v_2_0/Service', 'v_1_4_1/Service', 'v_2_0/Service', 'v_2_1/Service'],
    'BerkasKlaim' => ['Berkas', 'DokumenPendukung', 'Kelengkapan', 'KelengkapanKomentar', 'LabKlinik', 'LabKlinikDetil', 'ObatFarmasi', 'ObatFarmasiDetil', 'PatologiAnatomi', 'PatologiAnatomiDetil', 'Radiologi', 'RadiologiDetil'],
    'Cetakan' => ['KarcisPasien', 'KartuPasien', 'KwitansiPembayaran'],
    'DBService' => ['error/ErrorMessage', 'filter/Alnum', 'filter/Alpha', 'filter/Trim', 'generator/Generator', 'validator/Alnum', 'validator/Alpha', 'validator/Number', 'validator/Regex'],
    'Dashboard' => ['Indikator', 'KasusDiagnosa', 'KasusDiagnosaInacbg', 'KlaimIks', 'KlaimInacbg', 'Kunjungan', 'Laboratorium', 'Pendapatan', 'Penerimaan', 'Pengunjung', 'Radiologi', 'RawatInap', 'WaktuLayananRawatDarurat'],
    'DocumentStorage' => ['Document', 'DocumentDirectory'],
    'DukcapilService' => ['Dukcapil'],
    'General' => [
    'Administrasi',
    'Agama',
    'AlasanPembatalanKunjungan',
    'AlasanPembatalanPenerimaanBarang',
    'AlasanPembatalanRetur',
    'AntibiotikBakteri',
    'AturanPakai',
    'AturanPerhitunganAkomodasi',
    'Audios',
    'Bahasa',
    'Bank',
    'DepoLayananFarmasi',
    'Diagnosa',
    'DiagnosaMasuk',
    'DistribusiTarifPaket',
    'DistribusiTarifPaketDetil',
    'DistribusiTarifTindakan',
    'Dokter',
    'DokterRuangan',
    'DokterSMF',
    'DokumenScan',
    'Flow',
    'FrekuensiAturanResep',
    'FrekuensiAturanResepKategori',
    'GenerikZatAktif',
    'GolonganOperasi',
    'GroupLab',
    'GroupPemeriksaan',
    'GroupReferensiKelas',
    'GroupTindakanLab',
    'GroupUser',
    'IcdSnomedCt',
    'Instansi',
    'Jabatan',
    'JenisAbsen',
    'JenisAnastesi',
    'JenisBridge',
    'JenisCetak',
    'JenisDeposit',
    'JenisDiskon',
    'JenisIcd',
    'JenisItemPaket',
    'JenisKartuAsuransiPenjamin',
    'JenisKartuDebitKredit',
    'JenisKartuIdentitas',
    'JenisKelamin',
    'JenisKemasanRacikan',
    'JenisKontak',
    'JenisKunjungan',
    'JenisKunjunganRuangan',
    'JenisLaporan',
    'JenisLaporanDetil',
    'JenisOnsetPenilaianNyeri',
    'JenisOperasi',
    'JenisPPK',
    'JenisPasien',
    'JenisPelayananKesehatan',
    'JenisPembatalanRetur',
    'JenisPembayaran',
    'JenisPemberianObat',
    'JenisPemeriksaanPa',
    'JenisPenerimaan',
    'JenisPengguna',
    'JenisPenggunaanObat',
    'JenisPenjaminKecelakaan',
    'JenisPesertaPenjamin',
    'JenisPetugasMedis',
    'JenisRawatInap',
    'JenisResep',
    'JenisRuangan',
    'JenisRujukan',
    'JenisStatusLayananFarmasi',
    'JenisTagihan',
    'JenisTarif',
    'JenisTindakan',
    'JenisTransaksiPembayaranTagihan',
    'JenisTriwulan',
    'JenisWilayah',
    'KAP',
    'KIP',
    'KartuIdentitasKeluarga',
    'KategoriPenderitaTb',
    'KategoriTindakan',
    'KeadaanKeluar',
    'Kelas',
    'KelompokOperasi',
    'KelompokUmur',
    'KeluargaPasien',
    'KepemilikanTempatPelayanan',
    'KontakKeluargaPasien',
    'KontakPasien',
    'LayananLainnya',
    'LayananLainnyaTarif',
    'LockAksesPasien',
    'MappingGolonganBarangPenjamin',
    'MappingGroupPemeriksaan',
    'MappingRetriksiAntibiotik',
    'MappingRetriksiDiagnosa',
    'MappingRetriksiDpjp',
    'MappingRetriksiFormularium',
    'MappingRetriksiHari',
    'MappingRetriksiJumlah',
    'MappingRetriksiUnitAsalResep',
    'MarginPenjaminFarmasi',
    'MerkProdusen',
    'MetodeSkalaNyeri',
    'MorphologyIcdO',
    'NamaBulan',
    'Negara',
    'NilaiRujukanLab',
    'PPK',
    'Paket',
    'PaketDetil',
    'ParameterTindakanLab',
    'Pasien',
    'PayrollPenambah',
    'PayrollPengurang',
    'Pegawai',
    'Pekerjaan',
    'Pendidikan',
    'PenjaminRuangan',
    'PenjaminSubSpesialistik',
    'Perawat',
    'PerawatRuangan',
    'PeriodePerencanaan',
    'PetunjukRacikan',
    'PhotoPegawai',
    'Photopasien',
    'PpnPenjualan',
    'Profesi',
    'Prosedur',
    'Racikan',
    'Refrl',
    'Rekening',
    'RuangKamar',
    'RuangKamarTidur',
    'Ruangan',
    'RuanganFarmasi',
    'RuanganKelas',
    'RuanganKonsul',
    'RuanganLaboratorium',
    'RuanganLayananFarmasi',
    'RuanganMutasi',
    'RuanganOperasi',
    'RuanganRadiologi',
    'RuanganRujukan',
    'SMFRuangan',
    'SatuanLaboratorium',
    'SitbArt',
    'SitbBiakanSebelum',
    'SitbDm',
    'SitbHasilAkhirPengobatan',
    'SitbHasilFotoToraks',
    'SitbHasilTesHiv',
    'SitbJenisDiagnosis',
    'SitbJenisPerujuk',
    'SitbKlasifikasiLokasiAnatomi',
    'SitbKlasifikasiRiwayatPengobatan',
    'SitbKlasifikasiStatusHiv',
    'SitbMikroskopisAkhir',
    'SitbMikroskopisBulan2',
    'SitbMikroskopisBulan3',
    'SitbMikroskopisBulan5',
    'SitbMikroskopisSebelum',
    'SitbPaduanOat',
    'SitbPindahTb03Ro',
    'SitbPpk',
    'SitbScoringTbAnak0To13',
    'SitbScoringTbAnak5',
    'SitbScoringTbAnak6',
    'SitbStatusPengobatan',
    'SitbSumberObat',
    'SitbTcmSebelum',
    'SitbTerapiDm',
    'SitbToraksTidakDilakukan',
    'Smf',
    'Staff',
    'StaffRuangan',
    'StatusAktifitasKunjungan',
    'StatusAmbilPasien',
    'StatusHubunganDalamKeluarga',
    'StatusKepegawaian',
    'StatusKunjungan',
    'StatusLainnya',
    'StatusPasien',
    'StatusPegawai',
    'StatusPerkawinan',
    'StatusReservasi',
    'StatusRuangKamarTidur',
    'StatusRujukan',
    'Suku',
    'TarifAdministrasi',
    'TarifFarmasiPerKelas',
    'TarifO2',
    'TarifRuangRawat',
    'TarifTindakan',
    'TempatLahir',
    'TemplateAnatomi',
    'TenagaMedis',
    'Tindakan',
    'TindakanPaket',
    'TindakanRuangan',
    'TopographyIcdO',
    'Videos',
    'Wilayah',
    'YaTidak',
],
    'Generator' => ['Signature'],
    'INACBGService' => ['Grouper', 'Grouping', 'HasilGrouping', 'ICDINAGrouper', 'Inacbg', 'Komentar', 'ListProcedure', 'LogService', 'Map', 'TipeINACBG', 'V4/Service', 'V5/Service', 'V5/iDRG'],
    'Informasi' => ['InfromasiRuangKamarTidur', 'MonitoringSikepo'],
    'Inventory' => ['Barang', 'BarangRuangan', 'HargaBarang', 'Kategori', 'NoSeriBarangRuangan', 'PaketFarmasi', 'PembatalanPenerimaanBarang', 'Penerimaan', 'PenerimaanBarang', 'PenerimaanBarangDetil', 'PengembalianBarang', 'PengembalianBarangDetil', 'PenggolonganBarang', 'Pengiriman', 'PengirimanDetil', 'Penyedia', 'Permintaan', 'PermintaanDetil', 'Satuan', 'StokBarangMinimum', 'StokOpname', 'StokOpnameDetil', 'TransaksiStokRuangan'],
    'Kemkes' => ['BedMonitor', 'Bor', 'Dashboard', 'Diagnosa', 'DiagnosaRujukan10Besar', 'GolonganDarah', 'IHS/Account', 'IHS/AllergyIntolerance', 'IHS/BZA', 'IHS/BarangToBza', 'IHS/BarangToPoaPov', 'IHS/CarePlan', 'IHS/CarePlanJadwalKontrol', 'IHS/ClinicalImpression', 'IHS/CodeReference', 'IHS/Composition', 'IHS/Condition', 'IHS/ConditionAnamnesis', 'IHS/ConditionHasilPa', 'IHS/ConditionKeluhanUtama', 'IHS/ConditionPenilaianTumor', 'IHS/ConditionRiwayatPenyakitDahulu', 'IHS/Consent', 'IHS/Coverage', 'IHS/Dashboard', 'IHS/DiagnosticReport', 'IHS/EOF', 'IHS/Encounter', 'IHS/FormRegistry', 'IHS/ImagingStudy', 'IHS/KFA', 'IHS/KnowYourCustomer', 'IHS/Location', 'IHS/LocationRuangKamar', 'IHS/LocationTempatTidur', 'IHS/Loinc', 'IHS/Medication', 'IHS/MedicationDispanse', 'IHS/MedicationRequest', 'IHS/MedicationStatement', 'IHS/Observation', 'IHS/ObservationFaktorRisiko', 'IHS/ObservationPemeriksaanEkg', 'IHS/ObservationPenilaianGraceRiskSkor', 'IHS/ObservationRiwayatLainya', 'IHS/Organization', 'IHS/POA', 'IHS/POV', 'IHS/ParameterHasilToLoinc', 'IHS/Patient', 'IHS/Practitioner', 'IHS/Procedure', 'IHS/QuestionnaireResponse', 'IHS/SSRM', 'IHS/ServiceRequest', 'IHS/ServiceRequestJadwalKontrol', 'IHS/Sinkronisasi', 'IHS/SnomedCt', 'IHS/Specimen', 'IHS/SyncExecute', 'IHS/TindakanToLoinc', 'IHS/TypeCodeReference', 'Indikator', 'Kematian', 'Kunjungan', 'PendaftaranOnline', 'Penyakit10Besar', 'RSOnline/DataKebutuhanAPD', 'RSOnline/DataKebutuhanSDM', 'RSOnline/DataTempatTidur', 'RSOnline/DiagnosaPasien', 'RSOnline/KamarSimrsRsOnline', 'RSOnline/Pasien', 'RSOnline/Referensi', 'RSOnline/RekapPasienKeluar', 'RSOnline/RekapPasienKomorbid', 'RSOnline/RekapPasienMasuk', 'RSOnline/RekapPasienNonKomorbid', 'ReservasiAntrian', 'Rujukan', 'Run', 'SIRS/RL12', 'SIRS/RL13', 'SIRS/RL2', 'SIRS/RL31', 'SIRS/RL310', 'SIRS/RL311', 'SIRS/RL312', 'SIRS/RL313', 'SIRS/RL313b', 'SIRS/RL314', 'SIRS/RL315', 'SIRS/RL32', 'SIRS/RL33', 'SIRS/RL34', 'SIRS/RL35', 'SIRS/RL36', 'SIRS/RL37', 'SIRS/RL38', 'SIRS/RL39', 'SIRS/RL4a', 'SIRS/RL4aSebab', 'SIRS/RL4b', 'SIRS/RL4bSebab', 'SIRS/RL51', 'SIRS/RL52', 'SIRS/RL53', 'SIRS/RL54', 'SITB', 'Siranap', 'Sisrute', 'TerkonfirmasiTB'],
    'LISService' => ['HasilLog', 'HasilLogMicroAntibiotik', 'HasilLogMicroOrganism', 'MappingHasil', 'MappingHasilMicro', 'Parameter', 'ParameterMicro', 'PrefixParameter', 'Service', 'StatusHasil', 'TanpaOrderConfig', 'Vendor', 'lis', 'novanet', 'vanslab', 'winacom'],
    'Layanan' => ['BatasLayananObat', 'BonSisa', 'CatatanHasilLab', 'Farmasi', 'FarmasiKpo', 'FormulirAntimikroba', 'FormulirAntimikrobaApprove', 'FormulirAntimikrobaDetail', 'FormulirAntimikrobaHasilLab', 'FormulirAntimikrobaHasilLabMikro', 'FormulirAntimikrobaHasilPenunjangLain', 'FormulirAntimikrobaHasilRad', 'FormulirAntimikrobaPemeriksaanUmum', 'FormulirAntimikrobaRiwayatSebelumnya', 'HasilEvaluasiSST', 'HasilLab', 'HasilLabExam', 'HasilLabKepekaan', 'HasilLabKultur', 'HasilLabMikroskopik', 'HasilLabMikroskopikDetail', 'HasilLabPCR', 'HasilPa', 'HasilPemeriksaanImunoflurosensiPA', 'HasilPemeriksaanMolekulerPA', 'HasilRad', 'IterasiObat', 'JasaTuslahFarmasi', 'Kelahiran', 'LayananBonSisa', 'NilaiKritisLab', 'O2', 'OrderDetilLab', 'OrderDetilRad', 'OrderDetilResep', 'OrderLab', 'OrderRad', 'OrderResep', 'PasienMeninggal', 'PasienPulang', 'PemakaianBhp', 'PemakaianBhpDetil', 'PermintaanDarahDetail', 'PetugasTindakanMedis', 'ProtokolPengobatan', 'ProtokolPengobatanDetil', 'ProtokolPengobatanDetilObat', 'ResepTerlayaniKpo', 'ResepTerlayaniKpoDetil', 'ReturFarmasi', 'StatusHasilPemeriksaan', 'TelaahAwalResep', 'TindakanMedis', 'ViewerRad', 'WaktuPelayananKpo', 'WaktuPelayananKpoDetil'],
    'MedicalRecord' => ['Anamnesis', 'AnamnesisDiPeroleh', 'AsuhanKeperawatan', 'Batuk', 'CPPT', 'CPPTRawatBersama', 'CatatanImplementasi', 'DaftarImple', 'Diagnosa', 'DiagnosaFarmasi', 'DiagnosaKeperawatan', 'Diagnosis', 'DischargePlanningFaktorRisiko', 'DischargePlanningSkrining', 'EdukasiEmergency', 'EdukasiEndOfLife', 'EdukasiPasienKeluarga', 'FaktorEksternal', 'FaktorRisiko', 'Fibroscan', 'FinalBalance', 'Fungsional', 'HasilMCU', 'HubunganPsikososialEndOfLife', 'ICD10', 'ICD10Kematian', 'ICD9CM', 'Implementasi', 'ImplementasiAsuhanKeperawatan', 'ImplementasiIndikatorPerawatan', 'ImplementasiKeperawatan', 'ImunisasiPemberianVaksin', 'IndikatorKeperawatan', 'IntervensiRekomendasi', 'JadwalKontrol', 'JenisIndikatorKeperawatan', 'JenisPemeriksaan', 'KeluhanUtama', 'KondisiSosial', 'LembarTransferPasien', 'MappingIndikatorDiagnosa', 'MappingIntervensiIndikator', 'Obstetri', 'ObstetriKeluargaBerencana', 'Operasi', 'OperasiDiTindakan', 'PelaksanaOperasi', 'PemantuanHDIntradialitik', 'PemeriksaanAlergenHisap', 'PemeriksaanAlergenMakanan', 'PemeriksaanAnus', 'PemeriksaanAsessmentMchat', 'PemeriksaanBibir', 'PemeriksaanCatClams', 'PemeriksaanDada', 'PemeriksaanEeg', 'PemeriksaanEkg', 'PemeriksaanEmg', 'PemeriksaanFaring', 'PemeriksaanFisik', 'PemeriksaanGenital', 'PemeriksaanGigiGeligi', 'PemeriksaanHidung', 'PemeriksaanJariKaki', 'PemeriksaanJariTangan', 'PemeriksaanKepala', 'PemeriksaanKukuKaki', 'PemeriksaanKukuTangan', 'PemeriksaanLangitLangit', 'PemeriksaanLeher', 'PemeriksaanLenganAtas', 'PemeriksaanLenganBawah', 'PemeriksaanLidah', 'PemeriksaanMata', 'PemeriksaanObservasiTransfusiDarah', 'PemeriksaanPayudara', 'PemeriksaanPersendianKaki', 'PemeriksaanPersendianTangan', 'PemeriksaanPerut', 'PemeriksaanPrickTest', 'PemeriksaanProsedurKfr', 'PemeriksaanProsedurKfrDetail', 'PemeriksaanPunggung', 'PemeriksaanRambut', 'PemeriksaanRavenTest', 'PemeriksaanSaluranCernahAtas', 'PemeriksaanSaluranCernahBawah', 'PemeriksaanTcd', 'PemeriksaanTcdWindow', 'PemeriksaanTelinga', 'PemeriksaanTenggorokan', 'PemeriksaanTonsil', 'PemeriksaanTungkaiAtas', 'PemeriksaanTungkaiBawah', 'PemeriksaanUmum', 'PeminjamanBerkas', 'PenandaGambar', 'PenandaGambarDetail', 'PengkajianMpp', 'PenilaianBallanceCairan', 'PenilaianBallanceCairanDetail', 'PenilaianBarthelIndex', 'PenilaianBarthelIndexModifikasi', 'PenilaianDekubitus', 'PenilaianEpfra', 'PenilaianFisik', 'PenilaianGetUpAndGo', 'PenilaianGraceRiskSkor', 'PenilaianJantungKillipClass', 'PenilaianNyeri', 'PenilaianSkalaHumptyDumpty', 'PenilaianSkalaMorse', 'PenilaianTumor', 'PerencanaanRawatInap', 'PermasalahGiziPasien', 'PersetujuanTindakanDokter', 'PersetujuanTindakanDokterInformasi', 'PersetujuanTindakanDokterInformasiDetail', 'PersetujuanTindakanDokterPasien', 'PersetujuanTindakanPemberiInformasi', 'PersetujuanTindakanpenerimaInformasi', 'PersiapanAnastesi', 'PolaMakanNutrisi', 'PraAnastesiSedasi', 'ProtokolIntervensi', 'ProtokolIntervensiBAEP', 'ProtokolIntervensiBAEPdepresiDetail', 'ProtokolIntervensiBAEPdispagiaDetail', 'ProtokolIntervensiBAEPinsomniaDetail', 'ProtokolIntervensiBAEPkecemasanDetail', 'ProtokolIntervensiBAEPkognitifDetail', 'ProtokolIntervensiBAEPmotorikDetail', 'ProtokolIntervensiBAEPprotokolstimulasiDetail', 'ProtokolIntervensiBAEPsensorikDetail', 'ProtokolIntervensiDetail', 'RekonsiliasiAdmisi', 'RekonsiliasiAdmisiDetil', 'RekonsiliasiDischarge', 'RekonsiliasiDischargeDetil', 'RekonsiliasiTransfer', 'RekonsiliasiTransferDetil', 'RencanaDanTerapi', 'Resume', 'ResumeHasilLab', 'ResumeHasilLabDetil', 'ResumeHasilRad', 'ResumeHasilRadDetil', 'RiwayatAlergi', 'RiwayatGynekologi', 'RiwayatKehamilanIbu', 'RiwayatLainnya', 'RiwayatObstetri', 'RiwayatPemberianObat', 'RiwayatPenyakitKeluarga', 'RiwayatPenyakitTB', 'RiwayatPerawatan', 'RiwayatPerjalananPenyakit', 'RiwayatTindakanPembedahan', 'SkriningRiwayatKesehatanOrangTua', 'StatusFungsional', 'StatusPediatric', 'SuratHD', 'SuratKelahiran', 'SuratOpname', 'SuratSakit', 'SuratSehat', 'TandaVital', 'TindakanAbci', 'TindakanMMPI', 'TransfusiDarah', 'TransfusiDarahDetail', 'Triage', 'UploadDocument', 'UploadHasilPemeriksaanMata', 'UsgGiknekologi', 'UsgGuiding', 'VerifikasiCPPT'],
    'Monitoring' => ['DbSession'],
    'OpenAi' => ['ChatBot'],
    'Pasien' => ['Pasien'],
    'Pegawai' => ['KartuIdentitas', 'KontakPegawai', 'StrSip'],
    'Pembatalan' => ['FinalHasil', 'PembatalanDocument', 'PembatalanKunjungan', 'PembatalanRekamMedis', 'PembatalanRetur'],
    'Pembayaran' => ['Deposit', 'Diskon', 'DiskonDokter', 'EDC', 'GabungTagihan', 'Kasir', 'LayananPenyedia', 'PelunasanPiutangPasien', 'PelunasanPiutangPerusahaan', 'PembatalanTagihan', 'PembayaranTagihan', 'PengembalianDeposit', 'PenjaminTagihan', 'Penyedia', 'PiutangPasien', 'PiutangPerusahaan', 'RincianTagihan', 'RincianTagihanPaket', 'SubsidiTagihan', 'Tagihan', 'TagihanKlaim', 'TagihanPendaftaran', 'TransaksiKasir', 'Transfer'],
    'Pendaftaran' => ['AntrianRuangan', 'AntrianTempatTidur', 'Fungsi', 'History', 'JawabanKonsul', 'KIPPenanggungJawab', 'KartuIdentitasPengantarPasien', 'Kecelakaan', 'Konsul', 'KontakPenanggungJawab', 'KontakPengantarPasien', 'Kunjungan', 'Mutasi', 'PanggilanAntrianRuangan', 'PembatalanKunjungan', 'Pemohon', 'PenanggungJawabPasien', 'Pendaftaran', 'PenerimaanLayanan', 'PengantarPasien', 'Penjamin', 'PerubahanTanggalKunjungan', 'RawatBersama', 'Reservasi', 'RujukanKeluar', 'SuratRujukanPasien', 'TujuanPasien'],
    'PenjaminRS' => ['CaraKeluar', 'Dpjp', 'Drivers'],
    'Penjualan' => ['Penjualan', 'PenjualanDetil', 'ReturPenjualan'],
    'Plugins' => ['Bpjs', 'Dukcapil', 'Eklaim', 'Inacbg', 'Inasis', 'Kemkes', 'Pusdatin', 'RequestReport', 'TTS'],
    'Pusdatin' => ['Adminduk'],
    'ReportService' => ['Report'],
    'TTE' => ['Logs', 'Sign'],
    'TTS' => ['TTService'],
    'WABlas' => ['Message'],
    'fhir' => ['v3/administration', 'v3/clinical', 'v3/diagnostics', 'v3/foundation', 'v3/medication', 'v3/workflow', 'v5/administration', 'v5/clinical', 'v5/diagnostics', 'v5/foundation', 'v5/medication'],
];
